### ISSUE TITLE
Lecture 1.1 - Why do we need machine learning

### ISSUE THREAD

**Issue by WojciechSkumajTo** [WojciechSkumajTo/AI-Learning-Plan#1]
### Lecture 1.1 - Why do we need machine learning

**Description:**
Obejrzyj wykład "Lecture 1.1 — Why do we need machine learning — [ Deep Learning | Geoffrey Hinton | UofT ]" i zrób notatki w aplikacji GoodNotes. Prześlij notatki jako plik PDF do folderu `Lectures/`.

**Tasks:**
- [x] Obejrzyj wykład.
- [x] Zrób notatki w GoodNotes i wyeksportuj jako PDF.
- [x] Prześlij plik PDF do folderu `Lectures/Lecture_1.1_Why_do_we_need_machine_learning.pdf`.
- [x] Dodaj swoje przemyślenia i pytania do `README.md` w sekcji `Questions`.

**Estimated Time:** 60 minutes

**Due Date:** 16.07.2024

**Project:** AI Learning Plan
